general:
    name: "Kmeans experiment"
    folder_name: "kmeans_exp"
    seed: 12345
    
model:
    type: "Gaussian mixture"
    labels: ['1', '2']
    gaussian_1:
        mu: [0, 0]
        sigma: [[0.5, 0], [0, 10]]

    gaussian_2:
        mu: [3, 3]
        sigma: [[0.5, 0], [0, 0.5]]
        

    pi: [0.99, 0.01]

n_rep: 1
n_observations: 10000
subsets:
    n_subset: [5]
    subset_generation_method: "kmeans"
    n_clusters: 3 
