general:
    name: "Paper's gaussian experiment"
    folder_name: "paper_exp_gaussian"
    seed: 12345
    
model:
    type: "Gaussian mixture"
    labels: ['1', '2']
    gaussian_1:
        mu: [0, 0]
        sigma: [[5, 0], [0, 1]]

    gaussian_2:
        mu: [1, 0]
        sigma: [[0.5, 0], [0, 0.5]]
        

    pi: [0.8, 0.2]

n_rep: 1
n_observations: 10000
subsets:
    n_subset: [5, 10]
    subset_generation_method: "kmeans"
    n_clusters: 3 
