general:
    name: "Test"
    folder_name: "test"
    seed: 12345
    
model:
    type: "Gaussian mixture"
    labels: ['1', '2']
    gaussian_1:
        mu: [1, 2]
        sigma: [[1, 0.5], [0.5, 2]]

    gaussian_2:
        mu: [7, 8]
        sigma: [[1, 0.5], [0.5, 2]]

    pi: [0.3, 0.7]

n_rep: 1
n_observations: 100
subsets:
    n_subset: [5, 10]
    subset_generation_method: "kmeans"
    n_clusters: 3 
